### ISSUE TITLE
There is not sample

### ISSUE THREAD

**Issue by jycr753** [parris/react-clock-timepicker#3]
Looks like you deleted the sample page... do you have any other sample page?

**Comment by parris** [comment]
Yea... over the past few years its gone bad due to improved/changing SVG support in browsers. I figured no one was following this thing any more. BTW... I think https://github.com/frontsideair/react-clockpicker probably works way better at this point and has more active support. *thinking about killing this repo*

**Comment by jycr753** [comment]
thanks for the response, but yeah I end up using that one for the little thing I needed it . thanks
